### PR TITLE
New datasets

### PR DESCRIPTION
**Pull request by AliceFSmith**
I knew it should be this easy, 
csv file of 7 possible new data sets. Contains authors, journal, datadryad link in that order

### CODE REVIEW

**Comment by roblanf** [comment]
Hi Alice,

Nice one! All merged. I took a look at a couple and they look great.

Rob

On 13 March 2015 at 09:26, AliceFSmith <notifications@github.com> wrote:

> I knew it should be this easy,
> csv file of 7 possible new data sets. Contains authors, journal, datadryad
> link in that order
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/roblanf/PartitionedAlignments/pull/5
> Commit Summary
>
>    - Merge pull request #1 from roblanf/master
>    - New Datasets
>
> File Changes
>
>    - *A* datasets/Possible_Datasets.csv
>    <https://github.com/roblanf/PartitionedAlignments/pull/5/files#diff-0>
>    (1)
>
> Patch Links:
>
>    - https://github.com/roblanf/PartitionedAlignments/pull/5.patch
>    - https://github.com/roblanf/PartitionedAlignments/pull/5.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/roblanf/PartitionedAlignments/pull/5>.
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by BrianFoley** [comment]
I commented here yesterday, don't see my comment today.  I am a github novice.  Am I doing something wrong?

**Comment by roblanf** [comment]
Hi Brian,

You commented on the commit, not the merge. They are two different things.

Rob

On 14 March 2015 at 13:59, Brian Foley <notifications@github.com> wrote:

> I commented here yesterday, don't see my comment today. I am a github
> novice. Am I doing something wrong?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/roblanf/PartitionedAlignments/pull/5#issuecomment-79752094>
> .
>



-- 
Rob Lanfear
School of Biological Sciences,
Macquarie University,
Sydney

phone: +61 (0)2 9850 8204

www.robertlanfear.com

**Comment by BrianFoley** [comment]
2015_holmes_hivalign_tstvplotjpg

The data sets in the Duchene, Ho, Holmes Ts and Tv vs distance paper are fairly linear in comparison to data such as mitochondrial DNA within the mammals.  It would be interesting I have the Primate mitochondrial genomes aligned, if you would like to add that set.
00_april2015_primatelemur_tstvplotjpg

**Pull request merged**
