### PR TITLE
Master

### PR DESCRIPTION
**Pull request by terezasenfeldova**
some updates. fixed references. updating timetree stuff.

### CODE REVIEW

**Comment by roblanf** [comment]
Hi Tereza,

Are you sure all of these changes (you're submitting every change you've ever made) are complete, no errors, etc. Have you run the YAML checker on every YAML file? 

Rob

**Comment by terezasenfeldova** [comment]
Hello

I believe those changes are as far as I've gotten so far. I'm still working
through the timetree stuff.

Tereza

On Thu, Mar 10, 2016 at 1:25 PM, roblanf <notifications@github.com> wrote:

> Hi Tereza,
>
> Are you sure all of these changes (you're submitting every change you've
> ever made) are complete, no errors, etc. Have you run the YAML checker on
> every YAML file?
>
> Rob
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/roblanf/PartitionedAlignments/pull/18#issuecomment-194626056>
> .
>



-- 
-Tereza Senfeld

**Comment by roblanf** [comment]
OK, but the question is: are these changes all correct? Do all your YAML files pass the YAML checker? I know you renamed some files to do things (which is fine) but I want to keep the master version of the database clean and working at all times....

I'll have a look at your repo and see what I think, hold on...

**Comment by roblanf** [comment]
OK, I can see that things in your repo are a bit of a mess.

E.g. in this file: 

https://github.com/terezasenfeldova/PartitionedAlignments/tree/master/datasets/Siler_2013

You should have 2 files: alignment.nex and README.yaml

You have 4 files, with various names. 

So, I can't accept your pull request, becuase if I do that the working version of the database (which is the one you're asking me to change) will be broken.

What you need to do is go through and finalise everything so that it is complete, and once you are done (and you have checked everything with the YAML checker, and given me time to look through your changes too), submit a pull request. 

None of this is a big problem - it's just that it's not ready to be pulled over to this repo yet. 

For specific questions (e.g. on the timetree stuff) use the Slack channel, or raise an issue on my copy of the repo (the latter is better, see here: 

https://github.com/roblanf/PartitionedAlignments/issues

)

Keep up the good work!!

Rob

**Pull request closed without merging**
